### ISSUE TITLE
getting forbidden msg

### ISSUE THREAD

**Issue by eliaspizarro** [CactusSoft/zabbkit-android#1]
Can't add my previous server

![captura de pantalla 2017-05-10 19 47 13](https://cloud.githubusercontent.com/assets/8431845/25924656/41a40ae6-35ba-11e7-8570-3b25c3d6bb60.png)

Last version built from github, also with my phone and Gplay Zabbkit

**Comment by yan-oreshchenkov** [comment]
Check in debugger why you server returns 403. It doesn't look application issue.
