### ISSUE TITLE
The application does not start

### ISSUE THREAD

**Issue by Tikhonov1da** [CactusSoft/zabbkit-android#3]
Hello, I would like to ask you, because perhaps you know the reason - the application of zabbkit-android at startup produces an error. What can it be connected with?(Before that, I was able to fix the errors by updating the libraries)
![image](https://user-images.githubusercontent.com/50633106/57716338-f80ea680-76a2-11e9-8250-e341eac03156.png)

**Comment by yan-oreshchenkov** [comment]
The app is not supported anymore. As you noticed, a lot of libs were updated as well as Android platform itself. The app has fallen behind, nobody keep it up to date. I guess the error you faced with is related with this situation. We can't help you, sorry.
